source-file ~/.tmux.keybindings.conf
source-file ~/.tmux.appearance.conf

# don't rename windows automatically
set-option -g allow-rename off

# address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# tmux messages are displayed for 4 seconds
set -g display-time 4000

set-window-option -g xterm-keys on

set-option -g set-titles on
set-option -g set-titles-string "#S"

set -g base-index 1
setw -g pane-base-index 1

set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

set-option -g focus-events on

set -g mouse on

# Automatically rename the session when it is created
set-hook -g session-created "run-shell 'tmux rename-session \"\$(basename \$(git -C #{pane_current_path} rev-parse --show-toplevel 2>/dev/null || echo #{pane_current_path}))\"'"

# Set the status bar style
set -g status-style bg=black,fg=white

# Define the time format
set -g status-right "#[fg=cyan] %Y-%m-%d #[fg=yellow] %H:%M #[fg=default]"

# Set the status bar refresh interval (default is 15 seconds)
set -g status-interval 15

set-option -g history-limit 10000

set-option -g allow-passthrough all
